os:
  - linux

language: go

go:
  - 1.11.x

env:
  global:
    - GOTFLAGS="-race"
    - BUILD_DEPTYPE=gomod
  matrix:
    - TEST_PHASE=test
    - TEST_PHASE=benchmark

# disable travis install
install:
  - true

script:
  - ./bin/test-exec.sh

cache:
  directories:
    - $GOPATH/src/gx
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
